spring.datasource.url=jdbc:postgresql://localhost:5432/5HERTZ
spring.datasource.username=postgres
spring.datasource.password=mel2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081